### ISSUE TITLE
Adding OSINT source: Unit of interval unclear in UI

### ISSUE THREAD

**Issue by sebix** [SK-CERT/Taranis-NG#6]
When adding a new OSINT source, the form shows a field "Refresh interval". It is unclear for the user, which unit this is. Minutes? Seconds? Bananas?

**Comment by milankowww** [comment]
It's **seconds**. We are aware of this problem, it's one of the items in our TODO list before the official unveiling on November 10th, and will be fixed in coming days with many other GUI improvements.

**Comment by milankowww** [comment]
Fixed in 843a4feadcdbf3123f626e43e2d7d69a9eabd4a3.

**Comment by sebix** [comment]
So the unit was now changed from seconds to minutes?

**Comment by milankowww** [comment]
it never was in seconds, turns out I was just wrong. One of the improvements for the future include introducing more data types and some validation for collector-requested configuration. This way, some fields will be much easier to configure (radio for tor yes/no, pulldown for browser type, numbers for the interval).

**Comment by sebix** [comment]
> One of the improvements for the future include introducing more data types and some validation for collector-requested configuration. This way, some fields will be much easier to configure (radio for tor yes/no, pulldown for browser type, numbers for the interval).

Yeah, I have already seen the TODOs in the collectors' code :)
